version: '3'

services:
  db:
    image: mysql
    container_name: mysql_server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./src/main/scripts/mysql-setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql-data:/var/lib/mysql"

volumes:
  mysql-data: