version: '3'

services:
  db:
    image: mysql
    container_name: mysql_server
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./src/main/scripts/mysql-setup.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql-data:/var/lib/mysql"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote_app
    ports:
      - 8080:8080
    environment:
      SPRING_PROFILES_ACTIVE: mysql
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local