version: '3'

services:
  db:
    image: mysql
    container_name: mysql_server
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./src/main/scripts/mysql-setup.sql:/docker-entrypoint-initdb.d/1.sql"
#      - "./mysql-data:/var/lib/mysql"
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quote_app
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: mysql, redis
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quotes?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      REDIS_HOSTNAME: redis
    depends_on:
      - db
      - redis

#volumes:
#  mysql-data:
#    driver: local